apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: flagd-config
    behavior: replace
    options:
      disableNameSuffixHash: true
    files:
      - demo.flagd.json
