apiVersion: v2
name: astroshop
description: A Helm chart for Kubernetes
type: application
version: 0.3.12
appVersion: "2.1.3"
dependencies:
  - name: opentelemetry-demo
    version: 0.38.1
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
