apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: astroshop
    repo: oci://europe-docker.pkg.dev/dynatrace-demoability/helm
    version: 0.3.3
    releaseName: astroshop
    additionalValuesFiles:
      - values.yaml

namespace: astroshop

components:
  - ../components/ownership-labels
  - ../components/flagd-config
