components:
  ingress:
    enabled: false
    # host: ingress.host.com
  dt-credentials:
    enabled: true
    tenantEndpoint: https://wkf10640.live.dynatrace.com/api/v2/otlp
    tenantToken: dt0c01.abc.xxxXXXXXXXXXX
