name: Approve bot PR

on:
  pull_request:
    types:
      - opened
    paths:
      - flagd/flagd-config.yaml
      - image-provider/src/src/getProductImage.js

jobs:
  approve:
    name: Auto-approve
    runs-on: ubuntu-22.04
    if: github.event.pull_request.user.login == 'demoability-robot'
    steps:
      - name: Generate a token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/github-script@v7
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          script: |
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              event: "APPROVE"
            })
      - uses: actions/github-script@v7
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          script: |
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              merge_method: "squash"
            })
